import { v4 as uuidv4 } from 'uuid';
import { Block } from '@/types/pageBuilder';

export interface PageTemplate {
  id: string;
  name: { ar: string; en: string };
  description: { ar: string; en: string };
  category: 'general' | 'dev' | 'research';
  direction: 'rtl' | 'ltr';
  blocks: Record<string, any>[];
}

export const PAGE_TEMPLATES: PageTemplate[] = [
  {
    id: 'blank',
    name: { ar: 'صفحة فارغة', en: 'Blank Page' },
    description: { ar: 'ابدأ من الصفر', en: 'Start from scratch' },
    category: 'general',
    direction: 'rtl',
    blocks: [],
  },
  {
    id: 'landing-ar',
    name: { ar: 'صفحة هبوط عربية', en: 'Arabic Landing Page' },
    description: { ar: 'صفحة هبوط جاهزة بالعربية', en: 'Ready-made Arabic landing page' },
    category: 'general',
    direction: 'rtl',
    blocks: [
      { type: 'hero', title: 'مرحباً بكم في منصتنا', subtitle: 'نقدم لكم أفضل الحلول التقنية المبتكرة', buttonText: 'ابدأ الآن', buttonUrl: '#', variant: 'gradient' },
      { type: 'spacer', size: 'md' },
      { type: 'icon-card', icon: 'Rocket', title: 'سرعة فائقة', description: 'أداء عالي وسرعة استجابة ممتازة' },
      { type: 'icon-card', icon: 'Shield', title: 'أمان متقدم', description: 'حماية بيانات بأعلى المعايير' },
      { type: 'icon-card', icon: 'Zap', title: 'سهولة الاستخدام', description: 'واجهة بسيطة وسهلة التعلم' },
      { type: 'spacer', size: 'md' },
      { type: 'accordion', items: [
        { id: uuidv4(), question: 'ما هي الخدمات المقدمة؟', answer: 'نقدم مجموعة متنوعة من الخدمات التقنية' },
        { id: uuidv4(), question: 'كيف يمكنني البدء؟', answer: 'يمكنك التسجيل مجاناً والبدء فوراً' },
        { id: uuidv4(), question: 'هل هناك دعم فني؟', answer: 'نعم، فريق الدعم متاح على مدار الساعة' },
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'button', text: 'تواصل معنا', url: '#', variant: 'gradient', size: 'lg' },
    ],
  },
  {
    id: 'landing-en',
    name: { ar: 'صفحة هبوط إنجليزية', en: 'English Landing Page' },
    description: { ar: 'صفحة هبوط بالإنجليزية', en: 'Ready-made English landing page' },
    category: 'general',
    direction: 'ltr',
    blocks: [
      { type: 'hero', title: 'Welcome to Our Platform', subtitle: 'We provide innovative tech solutions to help you achieve your goals', buttonText: 'Get Started', buttonUrl: '#', variant: 'gradient' },
      { type: 'spacer', size: 'md' },
      { type: 'icon-card', icon: 'Rocket', title: 'Fast Performance', description: 'High performance and excellent response time' },
      { type: 'icon-card', icon: 'Shield', title: 'Advanced Security', description: 'Data protection with the highest standards' },
      { type: 'icon-card', icon: 'Zap', title: 'Easy to Use', description: 'Simple and intuitive interface' },
      { type: 'spacer', size: 'md' },
      { type: 'button', text: 'Get Started', url: '#', variant: 'gradient', size: 'lg' },
    ],
  },

  // ===== DEVELOPER TEMPLATES =====
  {
    id: 'api-docs',
    name: { ar: 'توثيق API', en: 'API Documentation' },
    description: { ar: 'قالب توثيق واجهة برمجية كامل', en: 'Full API reference template' },
    category: 'dev',
    direction: 'ltr',
    blocks: [
      { type: 'text', content: 'API Documentation', level: 'h1' },
      { type: 'text', content: 'Complete reference for the REST API endpoints, authentication, and usage examples.', level: 'p' },
      { type: 'divider', style: 'gradient' },
      { type: 'text', content: 'Authentication', level: 'h2' },
      { type: 'alert', message: 'All API requests require a valid API key in the Authorization header.', alertType: 'warning' },
      { type: 'terminal', title: 'Authentication Example', prompt: '$', commands: [
        '$ curl -H "Authorization: Bearer YOUR_API_KEY" \\',
        '  https://api.example.com/v1/users',
      ]},
      { type: 'spacer', size: 'md' },
      { type: 'text', content: 'Endpoints', level: 'h2' },
      { type: 'api', title: 'Users API', baseUrl: 'https://api.example.com/v1', methods: [
        { id: uuidv4(), method: 'GET', endpoint: '/users', description: 'List all users with pagination', params: 'page: number (default: 1)\nlimit: number (default: 20)', response: '{\n  "data": [{ "id": 1, "name": "John" }],\n  "total": 100\n}' },
        { id: uuidv4(), method: 'POST', endpoint: '/users', description: 'Create a new user', params: '{\n  "name": "string",\n  "email": "string",\n  "role": "admin" | "user"\n}', response: '{\n  "id": 1,\n  "name": "John",\n  "email": "john@example.com"\n}' },
        { id: uuidv4(), method: 'GET', endpoint: '/users/:id', description: 'Get user by ID', params: 'id: number (path parameter)', response: '{\n  "id": 1,\n  "name": "John",\n  "email": "john@example.com"\n}' },
        { id: uuidv4(), method: 'PUT', endpoint: '/users/:id', description: 'Update a user', params: '{\n  "name": "string",\n  "email": "string"\n}', response: '{\n  "id": 1,\n  "name": "John Updated"\n}' },
        { id: uuidv4(), method: 'DELETE', endpoint: '/users/:id', description: 'Delete a user', params: 'id: number (path parameter)', response: '{ "success": true }' },
      ]},
      { type: 'spacer', size: 'md' },
      { type: 'text', content: 'Error Codes', level: 'h2' },
      { type: 'table', headers: ['Code', 'Status', 'Description'], rows: [
        ['200', 'OK', 'Request succeeded'],
        ['201', 'Created', 'Resource created successfully'],
        ['400', 'Bad Request', 'Invalid request parameters'],
        ['401', 'Unauthorized', 'Missing or invalid API key'],
        ['404', 'Not Found', 'Resource not found'],
        ['429', 'Too Many Requests', 'Rate limit exceeded'],
        ['500', 'Server Error', 'Internal server error'],
      ]},
      { type: 'spacer', size: 'md' },
      { type: 'text', content: 'Rate Limiting', level: 'h2' },
      { type: 'text', content: 'API requests are limited to 100 requests per minute per API key.', level: 'p' },
      { type: 'progress', label: 'Rate Limit Usage Example', value: 73, max: 100, variant: 'warning' },
    ],
  },
  {
    id: 'project-readme',
    name: { ar: 'ملف README للمشروع', en: 'Project README' },
    description: { ar: 'قالب README احترافي لمشاريع GitHub', en: 'Professional README for GitHub projects' },
    category: 'dev',
    direction: 'ltr',
    blocks: [
      { type: 'text', content: '📦 Project Name', level: 'h1' },
      { type: 'text', content: 'A brief description of what this project does and who it\'s for.', level: 'p' },
      { type: 'divider', style: 'gradient' },
      { type: 'stats', items: [
        { id: uuidv4(), value: 'v2.1.0', label: 'Version', icon: 'Tag' },
        { id: uuidv4(), value: 'MIT', label: 'License', icon: 'Scale' },
        { id: uuidv4(), value: '1.2k', label: 'Stars', icon: 'Star' },
        { id: uuidv4(), value: '98%', label: 'Coverage', icon: 'Shield' },
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'Installation', level: 'h2' },
      { type: 'terminal', title: 'Install', prompt: '$', commands: [
        '$ git clone https://github.com/user/project.git',
        '$ cd project',
        '$ npm install',
        '$ cp .env.example .env',
        '$ npm run dev',
        '',
        'Server running at http://localhost:3000',
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'Project Structure', level: 'h2' },
      { type: 'file-tree', title: 'project/', items: [
        { id: uuidv4(), name: 'src', type: 'folder', indent: 0 },
        { id: uuidv4(), name: 'components', type: 'folder', indent: 1 },
        { id: uuidv4(), name: 'Button.tsx', type: 'file', indent: 2 },
        { id: uuidv4(), name: 'Card.tsx', type: 'file', indent: 2 },
        { id: uuidv4(), name: 'hooks', type: 'folder', indent: 1 },
        { id: uuidv4(), name: 'useAuth.ts', type: 'file', indent: 2 },
        { id: uuidv4(), name: 'lib', type: 'folder', indent: 1 },
        { id: uuidv4(), name: 'utils.ts', type: 'file', indent: 2 },
        { id: uuidv4(), name: 'App.tsx', type: 'file', indent: 1 },
        { id: uuidv4(), name: 'main.tsx', type: 'file', indent: 1 },
        { id: uuidv4(), name: 'package.json', type: 'file', indent: 0 },
        { id: uuidv4(), name: 'tsconfig.json', type: 'file', indent: 0 },
        { id: uuidv4(), name: 'README.md', type: 'file', indent: 0 },
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'Usage', level: 'h2' },
      { type: 'code', code: 'import { Button } from \'./components/Button\';\n\nfunction App() {\n  return (\n    <Button variant="primary" onClick={() => alert(\'Hello!\')}>\n      Click me\n    </Button>\n  );\n}', language: 'tsx', filename: 'App.tsx' },
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'Roadmap', level: 'h2' },
      { type: 'checklist', title: '', items: [
        { id: uuidv4(), text: 'Initial project setup', checked: true },
        { id: uuidv4(), text: 'Core components library', checked: true },
        { id: uuidv4(), text: 'Authentication system', checked: true },
        { id: uuidv4(), text: 'API integration', checked: false },
        { id: uuidv4(), text: 'Unit & E2E tests', checked: false },
        { id: uuidv4(), text: 'CI/CD pipeline', checked: false },
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'Contributing', level: 'h2' },
      { type: 'list', items: ['Fork the repository', 'Create a feature branch: git checkout -b feature/amazing', 'Commit your changes', 'Push and open a Pull Request'], ordered: true },
    ],
  },
  {
    id: 'changelog',
    name: { ar: 'سجل التغييرات', en: 'Changelog' },
    description: { ar: 'قالب سجل تحديثات المشروع', en: 'Project changelog template' },
    category: 'dev',
    direction: 'ltr',
    blocks: [
      { type: 'text', content: '📋 Changelog', level: 'h1' },
      { type: 'text', content: 'All notable changes to this project will be documented here.', level: 'p' },
      { type: 'divider', style: 'gradient' },
      { type: 'text', content: 'v2.1.0 — 2025-03-01', level: 'h2' },
      { type: 'alert', message: 'This release contains breaking changes in the API configuration.', alertType: 'warning' },
      { type: 'diff', title: 'Breaking Change: Config format updated', filename: 'config.ts', lines: [
        { id: uuidv4(), type: 'removed', content: 'export const config = { apiUrl: "..." };' },
        { id: uuidv4(), type: 'added', content: 'export const config = {' },
        { id: uuidv4(), type: 'added', content: '  api: { baseUrl: "...", version: "v2" },' },
        { id: uuidv4(), type: 'added', content: '  auth: { provider: "oauth2" },' },
        { id: uuidv4(), type: 'added', content: '};' },
      ]},
      { type: 'checklist', title: 'New Features', items: [
        { id: uuidv4(), text: 'Dark mode support', checked: true },
        { id: uuidv4(), text: 'Multi-language i18n', checked: true },
        { id: uuidv4(), text: 'Real-time collaboration', checked: true },
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'v2.0.0 — 2025-01-15', level: 'h2' },
      { type: 'timeline', items: [
        { id: uuidv4(), title: 'Complete UI redesign', description: 'Migrated from Material UI to shadcn/ui', date: 'Jan 15' },
        { id: uuidv4(), title: 'TypeScript migration', description: 'Full codebase converted to TypeScript', date: 'Jan 10' },
        { id: uuidv4(), title: 'Database restructure', description: 'Moved from MongoDB to PostgreSQL', date: 'Jan 5' },
      ]},
    ],
  },
  {
    id: 'sprint-board',
    name: { ar: 'لوحة سبرنت', en: 'Sprint Board' },
    description: { ar: 'قالب إدارة مهام الفريق', en: 'Team task management template' },
    category: 'dev',
    direction: 'ltr',
    blocks: [
      { type: 'text', content: '🏃 Sprint 14 — March 2025', level: 'h1' },
      { type: 'stats', items: [
        { id: uuidv4(), value: '24', label: 'Total Tasks', icon: 'ClipboardList' },
        { id: uuidv4(), value: '8', label: 'In Progress', icon: 'Loader' },
        { id: uuidv4(), value: '12', label: 'Completed', icon: 'CheckCircle' },
        { id: uuidv4(), value: '4', label: 'Blocked', icon: 'Ban' },
      ]},
      { type: 'progress', label: 'Sprint Progress', value: 67, max: 100, variant: 'primary' },
      { type: 'spacer', size: 'sm' },
      { type: 'kanban', title: 'Task Board', columns: [
        { id: uuidv4(), title: '📋 Backlog', items: ['Setup CI/CD pipeline', 'Write API docs', 'Design error pages'] },
        { id: uuidv4(), title: '🔄 In Progress', items: ['Implement user auth', 'Build dashboard UI'] },
        { id: uuidv4(), title: '👀 Review', items: ['Fix pagination bug', 'Update dependencies'] },
        { id: uuidv4(), title: '✅ Done', items: ['Setup project', 'Design system', 'DB schema'] },
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'Sprint Goals', level: 'h2' },
      { type: 'checklist', title: '', items: [
        { id: uuidv4(), text: 'Complete authentication flow', checked: true },
        { id: uuidv4(), text: 'Launch dashboard MVP', checked: false },
        { id: uuidv4(), text: 'API v2 endpoints ready', checked: false },
      ]},
    ],
  },

  // ===== RESEARCH TEMPLATES =====
  {
    id: 'research-paper',
    name: { ar: 'ورقة بحثية', en: 'Research Paper' },
    description: { ar: 'بحث أكاديمي مع مراجع واستشهادات', en: 'Academic paper with citations' },
    category: 'research',
    direction: 'ltr',
    blocks: [
      { type: 'text', content: 'Impact of Large Language Models on Software Engineering', level: 'h1' },
      { type: 'text', content: 'John Doe¹, Jane Smith², Robert Johnson¹', level: 'p' },
      { type: 'text', content: '¹ Computer Science Dept., MIT  •  ² Stanford AI Lab', level: 'p' },
      { type: 'divider', style: 'gradient' },
      { type: 'text', content: 'Abstract', level: 'h2' },
      { type: 'quote', text: 'This paper examines the transformative impact of Large Language Models on modern software engineering. Through a systematic review of 150 studies and a survey of 500 developers, we find that LLM-assisted development increases productivity by 35-45% while maintaining code quality.' },
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: '1. Introduction', level: 'h2' },
      { type: 'text', content: 'The emergence of Large Language Models has fundamentally changed how software is developed. Since GPT-3 in 2020, developers have increasingly relied on AI-powered tools for code generation, debugging, and documentation.', level: 'p' },
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: '2. Results', level: 'h2' },
      { type: 'table', headers: ['Metric', 'Control', 'LLM Group', 'Δ Change'], rows: [
        ['Lines of code/hour', '42.3', '58.7', '+38.8%'],
        ['Bug density (per KLOC)', '4.2', '3.8', '-9.5%'],
        ['Code review time (min)', '23.5', '15.2', '-35.3%'],
        ['Documentation coverage', '45%', '78%', '+73.3%'],
      ]},
      { type: 'stats', items: [
        { id: uuidv4(), value: '500+', label: 'Developers Surveyed', icon: 'Users' },
        { id: uuidv4(), value: '150', label: 'Papers Reviewed', icon: 'FileText' },
        { id: uuidv4(), value: '38.8%', label: 'Productivity Gain', icon: 'TrendingUp' },
      ]},
      { type: 'math', expression: 'Productivity = (T_manual - T_llm) / T_manual × 100%', label: 'Equation 1: Productivity metric', displayMode: true },
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'References', level: 'h2' },
      { type: 'citation', authors: 'Brown, T., Mann, B., Ryder, N., et al.', title: 'Language Models are Few-Shot Learners', source: 'NeurIPS 2020', year: '2020', doi: '10.48550/arXiv.2005.14165', url: 'https://arxiv.org/abs/2005.14165' },
      { type: 'citation', authors: 'Chen, M., Tworek, J., Jun, H., et al.', title: 'Evaluating Large Language Models Trained on Code', source: 'arXiv preprint', year: '2021', doi: '10.48550/arXiv.2107.03374' },
      { type: 'citation', authors: 'Vaithilingam, P., Zhang, T., Glassman, E.', title: 'Expectation vs. Experience: Evaluating Code Generation Tools', source: 'CHI 2022', year: '2022', doi: '10.1145/3491101.3519665' },
    ],
  },
  {
    id: 'literature-review',
    name: { ar: 'مراجعة أدبية', en: 'Literature Review' },
    description: { ar: 'مراجعة منهجية للأدبيات', en: 'Systematic literature review' },
    category: 'research',
    direction: 'ltr',
    blocks: [
      { type: 'text', content: 'Systematic Literature Review: Topic Name', level: 'h1' },
      { type: 'alert', message: 'This review follows the PRISMA 2020 guidelines for systematic reviews.', alertType: 'info' },
      { type: 'divider', style: 'gradient' },
      { type: 'text', content: 'Search Strategy', level: 'h2' },
      { type: 'table', headers: ['Database', 'Query', 'Results'], rows: [
        ['IEEE Xplore', '"machine learning" AND "testing"', '342'],
        ['ACM Digital Library', '"ML" AND "test generation"', '218'],
        ['Scopus', '"AI-driven" AND "quality assurance"', '156'],
        ['Google Scholar', '"deep learning" AND "automated testing"', '890'],
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'Selection Criteria', level: 'h2' },
      { type: 'checklist', title: 'Inclusion', items: [
        { id: uuidv4(), text: 'Peer-reviewed journals or conferences', checked: true },
        { id: uuidv4(), text: 'Published between 2019-2025', checked: true },
        { id: uuidv4(), text: 'Written in English', checked: true },
        { id: uuidv4(), text: 'Contains empirical evaluation', checked: true },
      ]},
      { type: 'checklist', title: 'Exclusion', items: [
        { id: uuidv4(), text: 'Workshop papers or extended abstracts only', checked: true },
        { id: uuidv4(), text: 'Duplicate publications', checked: true },
      ]},
      { type: 'spacer', size: 'sm' },
      { type: 'text', content: 'Selection Process', level: 'h2' },
      { type: 'timeline', items: [
        { id: uuidv4(), title: 'Initial search', description: '1,606 papers from 4 databases', date: 'Phase 1' },
        { id: uuidv4(), title: 'Duplicate removal', description: '423 removed → 1,183 papers', date: 'Phase 2' },
        { id: uuidv4(), title: 'Screening', description: '867 excluded → 316 papers', date: 'Phase 3' },
        { id: uuidv4(), title: 'Full-text review', description: '248 excluded → 68 included', date: 'Phase 4' },
      ]},
      { type: 'stats', items: [
        { id: uuidv4(), value: '1,606', label: 'Papers Found', icon: 'Search' },
        { id: uuidv4(), value: '68', label: 'Included', icon: 'FileCheck' },
        { id: uuidv4(), value: '4', label: 'Databases', icon: 'Database' },
      ]},
    ],
  },

  // ===== GENERAL =====
  {
    id: 'docs-ar',
    name: { ar: 'توثيق تقني عربي', en: 'Arabic Documentation' },
    description: { ar: 'صفحة توثيق تقنية', en: 'Technical documentation page' },
    category: 'general',
    direction: 'rtl',
    blocks: [
      { type: 'text', content: 'التوثيق التقني', level: 'h1' },
      { type: 'text', content: 'دليل شامل لاستخدام المنصة', level: 'h2' },
      { type: 'alert', message: 'تأكد من قراءة التوثيق كاملاً قبل البدء', alertType: 'info' },
      { type: 'code', code: 'npm install my-library\nnpm run dev', language: 'bash', filename: 'terminal' },
      { type: 'text', content: 'الإعدادات المتاحة', level: 'h3' },
      { type: 'table', headers: ['الإعداد', 'النوع', 'الافتراضي', 'الوصف'], rows: [
        ['theme', 'string', 'dark', 'سمة التطبيق'],
        ['lang', 'string', 'ar', 'لغة الواجهة'],
        ['rtl', 'boolean', 'true', 'دعم RTL'],
      ]},
      { type: 'list', items: ['تثبيت المكتبة', 'ضبط الإعدادات', 'إنشاء أول مشروع', 'نشر التطبيق'], ordered: true },
    ],
  },
  {
    id: 'showcase',
    name: { ar: 'عرض المكونات', en: 'Components Showcase' },
    description: { ar: 'معرض لكل أنواع البلوكات', en: 'Gallery of all block types' },
    category: 'general',
    direction: 'ltr',
    blocks: [
      { type: 'text', content: 'Component Showcase', level: 'h1' },
      { type: 'text', content: 'This page demonstrates all available block types.', level: 'p' },
      { type: 'divider', style: 'gradient' },
      { type: 'icon-card', icon: 'Star', title: 'Icon Card', description: 'A card with icon, title, and description' },
      { type: 'card', title: 'Default Card', content: 'Example card', variant: 'default' },
      { type: 'code', code: 'const hello = "world";\nconsole.log(hello);', language: 'javascript', filename: 'example.js' },
      { type: 'quote', text: 'Creativity is intelligence having fun.', author: 'Albert Einstein' },
      { type: 'alert', message: 'Informational alert', alertType: 'info' },
      { type: 'terminal', title: 'Terminal', prompt: '$', commands: ['$ echo "Hello World"', 'Hello World'] },
      { type: 'checklist', title: 'Sample Tasks', items: [
        { id: uuidv4(), text: 'Completed task', checked: true },
        { id: uuidv4(), text: 'Pending task', checked: false },
      ]},
      { type: 'math', expression: '∑(i=1 to n) i = n(n+1)/2', label: 'Sum formula', displayMode: true },
    ],
  },
];

export function createBlocksFromTemplate(template: PageTemplate): Block[] {
  return template.blocks.map((b, i) => ({
    ...b,
    id: uuidv4(),
    order: i,
  })) as Block[];
}
